export const data = [
  {
    "referenceId": "61338d5f2268fe6a7e7d6285",
    "assignee": "Tillman Duncan",
    "customerName": "Maldonado Rocha",
    "company": "Undertap",
    "customerEmail": "maldonado.rocha@undertap.com",
    "maskedPan": "826003XXXXXX7625",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-06-14T15:51:52.477Z",
    "description": "Culpa tempor elit fugiat fugiat reprehenderit cupidatat excepteur sint.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5f5ba83231bc916ee1",
    "assignee": "Lesa Aguilar",
    "customerName": "Lucas Haynes",
    "company": "Neocent",
    "customerEmail": "lucas.haynes@neocent.com",
    "maskedPan": "280720XXXXXX1756",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-06-20T22:33:09.234Z",
    "description": "Aliqua deserunt esse magna voluptate dolore consequat commodo.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5fe68103856e840d10",
    "assignee": "Harrington Donaldson",
    "customerName": "Laurel Day",
    "company": "Isologica",
    "customerEmail": "laurel.day@isologica.com",
    "maskedPan": "304594XXXXXX0483",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-06-15T00:30:47.457Z",
    "description": "Incididunt laboris culpa culpa in amet tempor ipsum reprehenderit sunt velit laborum incididunt consectetur eu.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f68de083a369a6107",
    "assignee": "Erin Allen",
    "customerName": "Rosa Fisher",
    "company": "Telepark",
    "customerEmail": "rosa.fisher@telepark.com",
    "maskedPan": "332032XXXXXX0155",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-03-12T13:02:36.551Z",
    "description": "Commodo laborum sint nostrud esse officia irure sint esse dolore adipisicing labore sint.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f2ad4d82d6f49024b",
    "assignee": "Wilkerson Dawson",
    "customerName": "Billie Blair",
    "company": "Electonic",
    "customerEmail": "billie.blair@electonic.com",
    "maskedPan": "188755XXXXXX5236",
    "type": "PAYOUT",
    "category": "COMPILANCE",
    "createdOn": "2021-03-19T21:58:17.294Z",
    "description": "Aute laborum velit Lorem aliquip cillum qui anim voluptate tempor incididunt tempor deserunt.",
    "status": "Approved"
  },
  {
    "referenceId": "61338d5fba9947162bcba741",
    "assignee": "Marci Frederick",
    "customerName": "Hannah Haley",
    "company": "Extrawear",
    "customerEmail": "hannah.haley@extrawear.com",
    "maskedPan": "263853XXXXXX3700",
    "type": "PAYOUT",
    "category": "RISK",
    "createdOn": "2021-09-02T01:57:37.693Z",
    "description": "Reprehenderit mollit fugiat anim magna amet nulla.",
    "status": "Approved"
  },
  {
    "referenceId": "61338d5f1fa8a2af9619952e",
    "assignee": "Browning Butler",
    "customerName": "Blake Barnes",
    "company": "Genmom",
    "customerEmail": "blake.barnes@genmom.com",
    "maskedPan": "918970XXXXXX8389",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-07-02T21:10:38.450Z",
    "description": "Laboris velit nulla consectetur exercitation sint elit fugiat sint irure dolore.",
    "status": "Approved"
  },
  {
    "referenceId": "61338d5f1750c1e886f2175b",
    "assignee": "Laura Booth",
    "customerName": "Katrina Franklin",
    "company": "Bizmatic",
    "customerEmail": "katrina.franklin@bizmatic.com",
    "maskedPan": "254200XXXXXX5394",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-04-23T14:54:43.654Z",
    "description": "Eu esse aliqua ea cupidatat ex est anim consectetur ex mollit irure.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5fd4ed7bfda8336a45",
    "assignee": "Gretchen Donovan",
    "customerName": "Morgan Barron",
    "company": "Zeam",
    "customerEmail": "morgan.barron@zeam.com",
    "maskedPan": "265889XXXXXX6542",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-08-05T23:37:17.448Z",
    "description": "Elit nostrud aliquip sunt nostrud deserunt culpa Lorem ipsum cillum ad.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5ffa29224dcbabf1c8",
    "assignee": "Stewart Flowers",
    "customerName": "Krystal Harmon",
    "company": "Wazzu",
    "customerEmail": "krystal.harmon@wazzu.com",
    "maskedPan": "001781XXXXXX8782",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-06-12T11:14:45.718Z",
    "description": "Ea est nulla incididunt laboris.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f0ada8578d0a5097d",
    "assignee": "Shepherd Campbell",
    "customerName": "Flossie Mejia",
    "company": "Entropix",
    "customerEmail": "flossie.mejia@entropix.com",
    "maskedPan": "467282XXXXXX7818",
    "type": "REFUND",
    "category": "RISK",
    "createdOn": "2021-04-27T03:22:05.986Z",
    "description": "Aute reprehenderit nostrud amet mollit aliqua consequat nisi officia ullamco in aliqua.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5f4c35cd8a70a865a3",
    "assignee": "Sonja Lloyd",
    "customerName": "Katina Peterson",
    "company": "Zillan",
    "customerEmail": "katina.peterson@zillan.com",
    "maskedPan": "591485XXXXXX1023",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-05-07T14:18:51.184Z",
    "description": "Id nisi laboris non proident quis labore nulla esse eiusmod ex cillum commodo velit.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f0742e4ff7becec2a",
    "assignee": "Sexton Shelton",
    "customerName": "Castillo Trujillo",
    "company": "Rockyard",
    "customerEmail": "castillo.trujillo@rockyard.com",
    "maskedPan": "046541XXXXXX4122",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-03-23T23:10:07.464Z",
    "description": "Ad esse reprehenderit eu enim excepteur mollit sit sint eiusmod.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f23dba1ad64b995d5",
    "assignee": "Tabatha Mendez",
    "customerName": "Walls Hood",
    "company": "Digirang",
    "customerEmail": "walls.hood@digirang.com",
    "maskedPan": "389208XXXXXX5014",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-04-30T02:48:53.989Z",
    "description": "Aute veniam labore elit dolor qui nisi occaecat ea exercitation esse voluptate elit do ullamco.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5f084551160d4dcb13",
    "assignee": "Le Barrera",
    "customerName": "Cunningham Carrillo",
    "company": "Liquicom",
    "customerEmail": "cunningham.carrillo@liquicom.com",
    "maskedPan": "897670XXXXXX1129",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-01-05T12:56:26.290Z",
    "description": "Est officia labore sit et adipisicing aliquip ex nisi incididunt tempor occaecat ea adipisicing.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5fd72137eb511c3438",
    "assignee": "Margaret Larson",
    "customerName": "Mercedes Newman",
    "company": "Zenolux",
    "customerEmail": "mercedes.newman@zenolux.com",
    "maskedPan": "430483XXXXXX4895",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-01-25T06:18:21.429Z",
    "description": "Duis consequat velit laboris cupidatat ad pariatur consequat.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5fe8323853b41b9180",
    "assignee": "Dickson Cook",
    "customerName": "Bailey Lane",
    "company": "Atomica",
    "customerEmail": "bailey.lane@atomica.com",
    "maskedPan": "126855XXXXXX3415",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-08-15T19:07:00.050Z",
    "description": "Magna reprehenderit do dolor qui.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5fe646b38facb9cde7",
    "assignee": "Norton Dorsey",
    "customerName": "Marsha Velazquez",
    "company": "Isologia",
    "customerEmail": "marsha.velazquez@isologia.com",
    "maskedPan": "826572XXXXXX5686",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-08-22T00:32:48.843Z",
    "description": "Cillum sunt dolor sit nisi irure.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5f608e162f1b45bc84",
    "assignee": "Marshall Carroll",
    "customerName": "Jill Jennings",
    "company": "Hyplex",
    "customerEmail": "jill.jennings@hyplex.com",
    "maskedPan": "333708XXXXXX3096",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-05-16T12:54:01.765Z",
    "description": "Dolore irure irure aute minim occaecat eu sint.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f594a334c8dd2f31d",
    "assignee": "Francis Burke",
    "customerName": "Valentine Bridges",
    "company": "Mediot",
    "customerEmail": "valentine.bridges@mediot.com",
    "maskedPan": "685439XXXXXX9545",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-01-08T20:26:14.469Z",
    "description": "Sint proident ex sunt mollit exercitation minim veniam adipisicing consectetur ut et ex eiusmod aute.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5ff1d72b22e355136f",
    "assignee": "Kenya Mcneil",
    "customerName": "Diana Brewer",
    "company": "Qualitex",
    "customerEmail": "diana.brewer@qualitex.com",
    "maskedPan": "270647XXXXXX1269",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-03-11T05:50:59.918Z",
    "description": "Culpa qui tempor nisi reprehenderit culpa aliquip aliquip sit labore.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5faf999bdc1f3a6078",
    "assignee": "Pearlie Ferrell",
    "customerName": "Powell Valentine",
    "company": "Austex",
    "customerEmail": "powell.valentine@austex.com",
    "maskedPan": "304864XXXXXX0645",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-02-05T10:55:37.046Z",
    "description": "Esse voluptate sit non mollit aliquip.",
    "status": "Approved"
  },
  {
    "referenceId": "61338d5f2249c193f5641aa1",
    "assignee": "Liza Aguirre",
    "customerName": "Marisol Macias",
    "company": "Netility",
    "customerEmail": "marisol.macias@netility.com",
    "maskedPan": "561772XXXXXX9564",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-03-19T07:41:52.642Z",
    "description": "Voluptate laboris cillum labore elit ad in tempor.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5facf9bdef97bacc18",
    "assignee": "Trevino Singleton",
    "customerName": "Arline Solomon",
    "company": "Petigems",
    "customerEmail": "arline.solomon@petigems.com",
    "maskedPan": "975403XXXXXX1691",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-09-01T22:55:58.414Z",
    "description": "Duis in cupidatat nisi ipsum do laboris nostrud amet duis et.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5faee3f449900bcd4e",
    "assignee": "Aurelia Kirkland",
    "customerName": "Osborne Lancaster",
    "company": "Renovize",
    "customerEmail": "osborne.lancaster@renovize.com",
    "maskedPan": "420478XXXXXX4541",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-08-11T12:51:15.147Z",
    "description": "Et adipisicing proident irure anim enim.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f5484f06c43a5a656",
    "assignee": "Casey Avila",
    "customerName": "Inez Poole",
    "company": "Architax",
    "customerEmail": "inez.poole@architax.com",
    "maskedPan": "771900XXXXXX7902",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-01-08T20:04:11.025Z",
    "description": "Nisi enim aliqua eu aliquip dolore nisi pariatur enim esse proident id.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5f100b003a71490efd",
    "assignee": "Warner Wilder",
    "customerName": "Singleton Nieves",
    "company": "Medcom",
    "customerEmail": "singleton.nieves@medcom.com",
    "maskedPan": "362589XXXXXX6799",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-04-20T09:13:39.550Z",
    "description": "Consectetur velit dolore id anim eiusmod ad velit adipisicing ut laborum et id excepteur.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5fba8e3b69d3473fb8",
    "assignee": "Roman Walls",
    "customerName": "Erika Bush",
    "company": "Anacho",
    "customerEmail": "erika.bush@anacho.com",
    "maskedPan": "900609XXXXXX7930",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-04-24T19:36:57.044Z",
    "description": "Aliquip deserunt minim consectetur id Lorem cillum adipisicing ex quis reprehenderit consectetur voluptate duis.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5f99623de22c86d5b0",
    "assignee": "Tran Kennedy",
    "customerName": "Faith Gallagher",
    "company": "Cinaster",
    "customerEmail": "faith.gallagher@cinaster.com",
    "maskedPan": "800517XXXXXX3003",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-01-04T16:06:47.252Z",
    "description": "Consectetur reprehenderit duis reprehenderit fugiat sunt occaecat.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5f5c3430b8705881f4",
    "assignee": "William Justice",
    "customerName": "Hall Baxter",
    "company": "Andryx",
    "customerEmail": "hall.baxter@andryx.com",
    "maskedPan": "339949XXXXXX4679",
    "type": "REFUND",
    "category": "RISK",
    "createdOn": "2021-08-15T20:59:17.599Z",
    "description": "Veniam laborum anim sit proident reprehenderit enim.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5f8a909d598562d4bb",
    "assignee": "David Miranda",
    "customerName": "Camille Figueroa",
    "company": "Fishland",
    "customerEmail": "camille.figueroa@fishland.com",
    "maskedPan": "928953XXXXXX6503",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-06-24T08:48:38.169Z",
    "description": "Eiusmod deserunt nostrud ipsum deserunt.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5f4d0038aa274712dd",
    "assignee": "Welch Gould",
    "customerName": "Marianne Bond",
    "company": "Elemantra",
    "customerEmail": "marianne.bond@elemantra.com",
    "maskedPan": "727281XXXXXX6290",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-03-28T08:55:20.764Z",
    "description": "Eiusmod sunt ut do mollit consectetur adipisicing veniam do minim velit est.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5fbeabf625e55789cf",
    "assignee": "Bernard Medina",
    "customerName": "Cathy Bowen",
    "company": "Rubadub",
    "customerEmail": "cathy.bowen@rubadub.com",
    "maskedPan": "395046XXXXXX6954",
    "type": "PAYOUT",
    "category": "RISK",
    "createdOn": "2021-01-31T00:06:44.188Z",
    "description": "Ea officia duis ut nisi adipisicing cupidatat ipsum fugiat anim esse.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5f1f46aa088e773650",
    "assignee": "Georgia Mckee",
    "customerName": "Greer Hutchinson",
    "company": "Newcube",
    "customerEmail": "greer.hutchinson@newcube.com",
    "maskedPan": "935134XXXXXX7278",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-07-25T05:31:45.366Z",
    "description": "Cillum deserunt aliquip ea cupidatat.",
    "status": "Approved"
  },
  {
    "referenceId": "61338d5fcefc92a3fda8535d",
    "assignee": "Guy Coffey",
    "customerName": "Baldwin Henry",
    "company": "Talae",
    "customerEmail": "baldwin.henry@talae.com",
    "maskedPan": "749599XXXXXX7537",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-07-20T22:07:32.882Z",
    "description": "Aliqua anim incididunt quis eiusmod elit consequat et id.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5f0a1e355159edfd6e",
    "assignee": "Mamie Haney",
    "customerName": "Mariana Lott",
    "company": "Comcur",
    "customerEmail": "mariana.lott@comcur.com",
    "maskedPan": "325721XXXXXX9942",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-08-03T22:25:26.544Z",
    "description": "Aliquip dolor aliqua nisi aliqua ad irure.",
    "status": "Approved"
  },
  {
    "referenceId": "61338d5f21b6e0a042401803",
    "assignee": "Stout Ruiz",
    "customerName": "Newton Ewing",
    "company": "Musanpoly",
    "customerEmail": "newton.ewing@musanpoly.com",
    "maskedPan": "857781XXXXXX3513",
    "type": "CHARGEBACK",
    "category": "COMPILANCE",
    "createdOn": "2021-01-18T05:28:51.590Z",
    "description": "Et sint in aute occaecat in.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5facfbd3685a1ca00c",
    "assignee": "Moreno Boyer",
    "customerName": "Joni Steele",
    "company": "Besto",
    "customerEmail": "joni.steele@besto.com",
    "maskedPan": "336648XXXXXX2605",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-08-30T01:21:48.314Z",
    "description": "Quis ad do et ullamco et officia cupidatat ullamco cupidatat nulla sunt eiusmod qui.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f391c3abd98122016",
    "assignee": "Koch Lewis",
    "customerName": "Reyna Swanson",
    "company": "Lexicondo",
    "customerEmail": "reyna.swanson@lexicondo.com",
    "maskedPan": "715844XXXXXX5677",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-05-14T05:00:01.443Z",
    "description": "Ut laborum nulla sint cillum irure enim aliquip.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5fbc10347fbbb1b53c",
    "assignee": "Marcella Alford",
    "customerName": "Leblanc Woodward",
    "company": "Qimonk",
    "customerEmail": "leblanc.woodward@qimonk.com",
    "maskedPan": "000129XXXXXX9039",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-06-16T10:48:32.439Z",
    "description": "Nostrud consectetur eu officia velit id amet reprehenderit.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5f5251ddc4405385f8",
    "assignee": "Dorothea Love",
    "customerName": "Taylor Ayers",
    "company": "Squish",
    "customerEmail": "taylor.ayers@squish.com",
    "maskedPan": "028663XXXXXX1174",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-06-12T15:35:14.199Z",
    "description": "Dolor mollit officia ullamco cupidatat nostrud tempor esse id.",
    "status": "Rejected"
  },
  {
    "referenceId": "61338d5f37caf89fc6267695",
    "assignee": "Burton Parrish",
    "customerName": "Hines Houston",
    "company": "Terrasys",
    "customerEmail": "hines.houston@terrasys.com",
    "maskedPan": "074695XXXXXX7869",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-06-11T18:47:03.565Z",
    "description": "Sint ut proident duis sint ipsum.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5f747e05fcd1f11034",
    "assignee": "Sullivan Freeman",
    "customerName": "Karina Dickerson",
    "company": "Turnabout",
    "customerEmail": "karina.dickerson@turnabout.com",
    "maskedPan": "221979XXXXXX5483",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-05-18T14:06:59.978Z",
    "description": "Tempor excepteur cupidatat id duis sunt irure sunt.",
    "status": "KYC Reviewed"
  },
  {
    "referenceId": "61338d5f93dba61a01e31310",
    "assignee": "Delores French",
    "customerName": "Hattie Workman",
    "company": "Neurocell",
    "customerEmail": "hattie.workman@neurocell.com",
    "maskedPan": "225659XXXXXX7993",
    "type": "PAYMENT",
    "category": "RISK",
    "createdOn": "2021-01-22T05:42:49.914Z",
    "description": "Excepteur eiusmod culpa eu labore Lorem nulla voluptate ipsum.",
    "status": "Open"
  },
  {
    "referenceId": "61338d5f4384facff166d870",
    "assignee": "Bell Griffin",
    "customerName": "Adrienne Mcclain",
    "company": "Geoform",
    "customerEmail": "adrienne.mcclain@geoform.com",
    "maskedPan": "677995XXXXXX1193",
    "type": "PAYMENT",
    "category": "COMPILANCE",
    "createdOn": "2021-08-24T06:47:08.150Z",
    "description": "Voluptate officia laborum incididunt aliquip reprehenderit velit do labore.",
    "status": "In review"
  },
  {
    "referenceId": "61338d5f99b5ee9c245ad297",
    "assignee": "Mayo Mcconnell",
    "customerName": "Woodard Pate",
    "company": "Idetica",
    "customerEmail": "woodard.pate@idetica.com",
    "maskedPan": "607292XXXXXX4233",
    "type": "CHARGEBACK",
    "category": "COMPILANCE",
    "createdOn": "2021-07-13T13:55:46.732Z",
    "description": "Magna anim nisi esse nulla ex do dolore anim nostrud officia anim deserunt consequat commodo.",
    "status": "In review"
  }
]